CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNITY_PRICE NUMERIC(20,2)
);

CREATE TABLE "ORDERS" (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDER_DATE TIMESTAMP,
    PRICE NUMERIC(20,2)
);

CREATE TABLE ORDER_ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES "ORDERS" (ID),
    ITEM_ID INTEGER REFERENCES ITEM (ID),
    QUANTITY INTEGER
);