spring.config.activate.on-profile=dev

spring.security.user.password=password
spring.jpa.show-sql=true
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE